spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      routes:
        - id: main-admin
          uri: lb://main-server
          predicates:
            - Path=/admin/**
        - id: main-users
          uri: lb://main-server
          predicates:
            - Path=/users/**
        - id: main-events
          uri: lb://main-server
          predicates:
            - Path=/events/**
        - id: main-categories
          uri: lb://main-server
          predicates:
            - Path=/categories/**
        - id: main-compilations
          uri: lb://main-server
          predicates:
            - Path=/compilations/**
        - id: main-locations
          uri: lb://main-server
          predicates:
            - Path=/locations/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
